--liquibase formatted sql

--changeset ali:001-create-ticket-analysis
--preconditions onFail:MARK_RAN onError:HALT
--precondition-sql-check expectedResult:0 SELECT COUNT(*) FROM information_schema.tables WHERE table_name = 'ticket_analysis';
CREATE TABLE ticket_analysis (
     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
     subject VARCHAR(120) NOT NULL,
     body VARCHAR(5000) NOT NULL,
     customer_id VARCHAR(80),
     analysis_source VARCHAR(80) NOT NULL,
     status VARCHAR(40) NOT NULL,
     category VARCHAR(40) NOT NULL,
     priority VARCHAR(40) NOT NULL,
     customer_intent VARCHAR(500) NOT NULL
);